language: go
go_import_path: github.com/NextronSystems/go-elasticsearch
notifications:
  email: false
  slack: nextron-systems:51vB5h6MxkSbX5iMpscrvOza
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.1.1.deb && sudo service elasticsearch restart
before_script:
  - sleep 15
